#[derive(Debug, Clone, PartialEq, Eq)]
pub enum Op {
    Cls,
    Ret,
    Jp { nnn: u16 },
    Call { nnn: u16 },
    SeByte { x: u8, kk: u8 },
    SneByte { x: u8, kk: u8 },
    SeReg { x: u8, y: u8 },
    LdByte { x: u8, kk: u8 },
    AddByte { x: u8, kk: u8 },
    LdReg { x: u8, y: u8 },
    Or { x: u8, y: u8 },
    And { x: u8, y: u8 },
    Xor { x: u8, y: u8 },
    AddReg { x: u8, y: u8 },
    Sub { x: u8, y: u8 },
    Shr { x: u8 },
    Subn { x: u8, y: u8 },
    Shl { x: u8 },
    SneReg { x: u8, y: u8 },
    LdI { nnn: u16 },
    JpV0 { nnn: u16 },
    Rnd { x: u8, kk: u8 },
    Drw { x: u8, y: u8, n: u8 },
    Skp { x: u8 },
    Sknp { x: u8 },
    LdVxDt { x: u8 },
    LdVxK { x: u8 },
    LdDtVx { x: u8 },
    LdStVx { x: u8 },
    AddI { x: u8 },
    LdF { x: u8 },
    Bcd { x: u8 },
    StoreRegs { x: u8 },
    LoadRegs { x: u8 },
    Unknown { opcode: u16 },
}
