use std::fmt::{self, Display, Formatter, Write as _};

use crate::compiler::ir::{BlockIr, EffectIr, ProgramIr, TerminatorIr};

const WGSL_BOILERPLATE: &str = "// CHIP-8 compiled shader - generated by chip8-frag compiler.\n\n\
alias BlockId = u32;\n\n\
struct VmState {\n\
    block_id: BlockId,\n\
    i_reg: u32,\n\
    sp: u32,\n\
    delay_timer: u32,\n\
    sound_timer: u32,\n\
    rng_state: u32,\n\
    v: array<u32, 4>,\n\
    stack: array<u32, 8>,\n\
    memory: array<u32, 1024>,\n\
}\n\n\
@group(0) @binding(0) var<storage, read_write> vm: VmState;\n\
@group(0) @binding(1) var<storage, read_write> display: array<u32, 2048>;\n\
@group(0) @binding(2) var<storage, read>       keypad:  array<u32, 16>;\n\n\
const CYCLES_PER_FRAME: u32 = 10u;\n\n";

const WGSL_HELPERS: &str = "fn mem_read(addr: u32) -> u32 {\n\
    let word_idx = addr >> 2u;\n\
    let byte_idx = addr & 3u;\n\
    return (vm.memory[word_idx] >> (byte_idx * 8u)) & 0xFFu;\n\
}\n\n\
fn mem_write(addr: u32, val: u32) {\n\
    let word_idx = addr >> 2u;\n\
    let byte_idx = addr & 3u;\n\
    let shift = byte_idx * 8u;\n\
    let mask = ~(0xFFu << shift);\n\
    vm.memory[word_idx] = (vm.memory[word_idx] & mask) | ((val & 0xFFu) << shift);\n\
}\n\n\
fn reg_read(idx: u32) -> u32 {\n\
    let word_idx = idx >> 2u;\n\
    let byte_idx = idx & 3u;\n\
    return (vm.v[word_idx] >> (byte_idx * 8u)) & 0xFFu;\n\
}\n\n\
fn reg_write(idx: u32, val: u32) {\n\
    let word_idx = idx >> 2u;\n\
    let byte_idx = idx & 3u;\n\
    let shift = byte_idx * 8u;\n\
    let mask = ~(0xFFu << shift);\n\
    vm.v[word_idx] = (vm.v[word_idx] & mask) | ((val & 0xFFu) << shift);\n\
}\n\n\
fn stack_read(idx: u32) -> u32 {\n\
    let word_idx = idx >> 1u;\n\
    let half_idx = idx & 1u;\n\
    return (vm.stack[word_idx] >> (half_idx * 16u)) & 0xFFFFu;\n\
}\n\n\
fn stack_write(idx: u32, val: u32) {\n\
    let word_idx = idx >> 1u;\n\
    let half_idx = idx & 1u;\n\
    let shift = half_idx * 16u;\n\
    let mask = ~(0xFFFFu << shift);\n\
    vm.stack[word_idx] = (vm.stack[word_idx] & mask) | ((val & 0xFFFFu) << shift);\n\
}\n\n\
fn xorshift() -> u32 {\n\
    var s = vm.rng_state;\n\
    s ^= s << 13u;\n\
    s ^= s >> 17u;\n\
    s ^= s << 5u;\n\
    vm.rng_state = s;\n\
    return s;\n\
}\n\n";

struct EffectDisplay<'a>(&'a EffectIr);

impl Display for EffectDisplay<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match *self.0 {
            EffectIr::ClearDisplay => {
                write!(
                    f,
                    "    for (var idx = 0u; idx < 2048u; idx++) {{\n        display[idx] = 0u;\n    }}\n"
                )
            }
            EffectIr::SetRegImm { x, kk } => writeln!(f, "    reg_write({x}u, {kk}u);"),
            EffectIr::AddRegImm { x, kk } => {
                writeln!(f, "    reg_write({x}u, (reg_read({x}u) + {kk}u) & 0xFFu);")
            }
            EffectIr::SetRegReg { x, y } => writeln!(f, "    reg_write({x}u, reg_read({y}u));"),
            EffectIr::Or { x, y } => {
                writeln!(f, "    reg_write({x}u, reg_read({x}u) | reg_read({y}u));")
            }
            EffectIr::And { x, y } => {
                writeln!(f, "    reg_write({x}u, reg_read({x}u) & reg_read({y}u));")
            }
            EffectIr::Xor { x, y } => {
                writeln!(f, "    reg_write({x}u, reg_read({x}u) ^ reg_read({y}u));")
            }
            EffectIr::AddReg { x, y } => write!(
                f,
                "    let sum = reg_read({x}u) + reg_read({y}u);\n    reg_write({x}u, sum & 0xFFu);\n    reg_write(0xFu, u32(sum > 0xFFu));\n"
            ),
            EffectIr::SubReg { x, y } => write!(
                f,
                "    let vx = reg_read({x}u);\n    let vy = reg_read({y}u);\n    reg_write({x}u, (vx - vy) & 0xFFu);\n    reg_write(0xFu, u32(vx >= vy));\n"
            ),
            EffectIr::Shr { x } => write!(
                f,
                "    let vx = reg_read({x}u);\n    reg_write({x}u, vx >> 1u);\n    reg_write(0xFu, vx & 1u);\n"
            ),
            EffectIr::SubnReg { x, y } => write!(
                f,
                "    let vx = reg_read({x}u);\n    let vy = reg_read({y}u);\n    reg_write({x}u, (vy - vx) & 0xFFu);\n    reg_write(0xFu, u32(vy >= vx));\n"
            ),
            EffectIr::Shl { x } => write!(
                f,
                "    let vx = reg_read({x}u);\n    reg_write({x}u, (vx << 1u) & 0xFFu);\n    reg_write(0xFu, (vx >> 7u) & 1u);\n"
            ),
            EffectIr::SetI { nnn } => writeln!(f, "    vm.i_reg = 0x{nnn:03X}u;"),
            EffectIr::RandMask { x, kk } => {
                writeln!(f, "    reg_write({x}u, xorshift() & {kk}u & 0xFFu);")
            }
            EffectIr::Draw { x, y, n } => write!(
                f,
                "    let vx = reg_read({x}u) % 64u;\n    let vy = reg_read({y}u) % 32u;\n    var collision = 0u;\n    for (var row = 0u; row < {n}u; row++) {{\n        let sprite_byte = mem_read(vm.i_reg + row);\n        for (var col = 0u; col < 8u; col++) {{\n            if (sprite_byte & (0x80u >> col)) != 0u {{\n                let px = (vx + col) % 64u;\n                let py = (vy + row) % 32u;\n                let didx = py * 64u + px;\n                if display[didx] != 0u {{\n                    collision = 1u;\n                }}\n                display[didx] ^= 1u;\n            }}\n        }}\n    }}\n    reg_write(0xFu, collision);\n"
            ),
            EffectIr::LoadDelayToV { x } => {
                writeln!(f, "    reg_write({x}u, vm.delay_timer & 0xFFu);")
            }
            EffectIr::SetDelayFromV { x } => writeln!(f, "    vm.delay_timer = reg_read({x}u);"),
            EffectIr::SetSoundFromV { x } => writeln!(f, "    vm.sound_timer = reg_read({x}u);"),
            EffectIr::AddIFromV { x } => {
                writeln!(f, "    vm.i_reg = (vm.i_reg + reg_read({x}u)) & 0xFFFu;")
            }
            EffectIr::SetIFont { x } => writeln!(f, "    vm.i_reg = 0x050u + reg_read({x}u) * 5u;"),
            EffectIr::Bcd { x } => write!(
                f,
                "    let val = reg_read({x}u);\n    mem_write(vm.i_reg,      val / 100u);\n    mem_write(vm.i_reg + 1u, (val / 10u) % 10u);\n    mem_write(vm.i_reg + 2u, val % 10u);\n"
            ),
            EffectIr::StoreRegs { x } => write!(
                f,
                "    for (var r = 0u; r <= {x}u; r++) {{\n        mem_write(vm.i_reg + r, reg_read(r));\n    }}\n"
            ),
            EffectIr::LoadRegs { x } => write!(
                f,
                "    for (var r = 0u; r <= {x}u; r++) {{\n        reg_write(r, mem_read(vm.i_reg + r));\n    }}\n"
            ),
            EffectIr::Unknown { opcode } => {
                writeln!(f, "    // unknown opcode 0x{opcode:04X} - no-op")
            }
        }
    }
}

struct TerminatorDisplay<'a>(&'a TerminatorIr);

impl Display for TerminatorDisplay<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        match *self.0 {
            TerminatorIr::Goto { target } => writeln!(f, "    vm.block_id = {target}u;"),
            TerminatorIr::Call { target, ret } => write!(
                f,
                "    stack_write(vm.sp, {ret}u);\n    vm.sp += 1u;\n    vm.block_id = {target}u;\n"
            ),
            TerminatorIr::Return => {
                write!(
                    f,
                    "    vm.sp -= 1u;\n    vm.block_id = stack_read(vm.sp);\n"
                )
            }
            TerminatorIr::BranchEqImm {
                x,
                kk,
                then_target,
                else_target,
            } => write!(
                f,
                "    if reg_read({x}u) == {kk}u {{\n        vm.block_id = {then_target}u;\n    }} else {{\n        vm.block_id = {else_target}u;\n    }}\n"
            ),
            TerminatorIr::BranchNeImm {
                x,
                kk,
                then_target,
                else_target,
            } => write!(
                f,
                "    if reg_read({x}u) != {kk}u {{\n        vm.block_id = {then_target}u;\n    }} else {{\n        vm.block_id = {else_target}u;\n    }}\n"
            ),
            TerminatorIr::BranchEqReg {
                x,
                y,
                then_target,
                else_target,
            } => write!(
                f,
                "    if reg_read({x}u) == reg_read({y}u) {{\n        vm.block_id = {then_target}u;\n    }} else {{\n        vm.block_id = {else_target}u;\n    }}\n"
            ),
            TerminatorIr::BranchNeReg {
                x,
                y,
                then_target,
                else_target,
            } => write!(
                f,
                "    if reg_read({x}u) != reg_read({y}u) {{\n        vm.block_id = {then_target}u;\n    }} else {{\n        vm.block_id = {else_target}u;\n    }}\n"
            ),
            TerminatorIr::BranchKeyPressed {
                x,
                then_target,
                else_target,
            } => write!(
                f,
                "    if keypad[reg_read({x}u) & 0xFu] != 0u {{\n        vm.block_id = {then_target}u;\n    }} else {{\n        vm.block_id = {else_target}u;\n    }}\n"
            ),
            TerminatorIr::BranchKeyNotPressed {
                x,
                then_target,
                else_target,
            } => write!(
                f,
                "    if keypad[reg_read({x}u) & 0xFu] == 0u {{\n        vm.block_id = {then_target}u;\n    }} else {{\n        vm.block_id = {else_target}u;\n    }}\n"
            ),
            TerminatorIr::WaitKey {
                x,
                on_found,
                on_not_found,
            } => write!(
                f,
                "    var found = false;\n    for (var k = 0u; k < 16u; k++) {{\n        if keypad[k] != 0u {{\n            reg_write({x}u, k);\n            found = true;\n            break;\n        }}\n    }}\n    if found {{\n        vm.block_id = {on_found}u;\n    }} else {{\n        vm.block_id = {on_not_found}u;\n    }}\n"
            ),
            TerminatorIr::JumpV0 { base } => write!(
                f,
                "    vm.block_id = address_to_block((0x{base:03X}u + reg_read(0u)) & 0xFFFu);\n"
            ),
        }
    }
}

struct BlockDisplay<'a>(&'a BlockIr);

impl Display for BlockDisplay<'_> {
    fn fmt(&self, f: &mut Formatter<'_>) -> fmt::Result {
        writeln!(f, "fn block_{}() {{", self.0.id)?;
        for effect in &self.0.effects {
            writeln!(f, "    {{")?;
            write!(f, "{}", EffectDisplay(effect))?;
            writeln!(f, "    }}")?;
        }
        write!(f, "{}", TerminatorDisplay(&self.0.term))?;
        writeln!(f, "}}")
    }
}

fn render_raw(program: &ProgramIr) -> String {
    let mut out = String::with_capacity(32 * 1024);
    out.push_str(WGSL_BOILERPLATE);
    out.push_str(WGSL_HELPERS);

    out.push_str("fn address_to_block(addr: u32) -> BlockId {\n    switch addr {\n");
    for (addr, block) in &program.addr_to_block {
        let _ = writeln!(out, "        case 0x{addr:03X}u {{ return {block}u; }}");
    }
    out.push_str("        default { return vm.block_id; }\n    }\n}\n\n");

    for block in &program.blocks {
        let _ = write!(out, "{}\n", BlockDisplay(block));
    }

    out.push_str("fn execute_cycle() {\n    switch vm.block_id {\n");
    for block in &program.blocks {
        let _ = writeln!(
            out,
            "        case {}u {{ block_{}(); }}",
            block.id, block.id
        );
    }
    out.push_str("        default {}\n    }\n}\n\n");

    out.push_str("@compute @workgroup_size(1)\nfn main() {\n    for (var cycle = 0u; cycle < CYCLES_PER_FRAME; cycle++) {\n        execute_cycle();\n    }\n\n    if vm.delay_timer > 0u {\n        vm.delay_timer -= 1u;\n    }\n    if vm.sound_timer > 0u {\n        vm.sound_timer -= 1u;\n    }\n}\n");

    if program.blocks.is_empty() {
        out.push_str("\n// empty ROM: no executable blocks emitted\n");
    }

    out
}

pub(super) fn emit_wgsl(program: &ProgramIr) -> String {
    let raw = render_raw(program);
    let module = naga::front::wgsl::parse_str(&raw).expect("generated WGSL failed to parse");

    let mut validator = naga::valid::Validator::new(
        naga::valid::ValidationFlags::all(),
        naga::valid::Capabilities::all(),
    );
    let info = validator
        .validate(&module)
        .expect("generated WGSL failed naga validation");

    naga::back::wgsl::write_string(
        &module,
        &info,
        naga::back::wgsl::WriterFlags::EXPLICIT_TYPES,
    )
    .expect("naga failed to write WGSL")
}
